name: Build Notebooks
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install jupytext nbconvert

      - name: Build notebooks
        run: |
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 01_CARE/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 01_CARE/solution.py --output 01_CARE/exercise.ipynb
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 02_Noise2Void/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 02_Noise2Void/solution.py --output 02_Noise2Void/exercise.ipynb
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 03_COSDD/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 03_COSDD/solution.py --output 03_COSDD/exercise.ipynb
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 03_COSDD/bonus-solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 03_COSDD/bonus-solution.py --output 03_COSDD/bonus-exercise.ipynb
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 04_MicroSplit/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 04_MicroSplit/solution.py --output 04_MicroSplit/exercise.ipynb
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 05_bonus_Noise2Noise/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update 05_bonus_Noise2Noise/solution.py --output 05_bonus_Noise2Noise/exercise.ipynb
      - uses: EndBug/add-and-commit@v9
        with:
          add: "*.ipynb"
